# Generated by Django 6.0.1 on 2026-01-28 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
                ('date_time', models.DateTimeField()),
                ('duration', models.IntegerField()),
                ('status', models.CharField(max_length=50)),
                ('remarks', models.TextField(blank=True)),
            ],
        ),
    ]
